### ISSUE TITLE
Teknisk Kontakter-list sometimes doesnt show details

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-kunde-portal-frontend#17]
When I enter https://kunde.felleskomponent.no/contacts, the contacts-details sometimes doesnt show up: 
 
![image](https://user-images.githubusercontent.com/36536861/62551338-1b915980-b86c-11e9-8abb-39b11d0e5bdc.png)

When I retry it show up.

**Comment by fsjovatsen** [comment]
This needs to be fixed in the backend. 

Spring LDAP plugin sometimes don't deserialize properly. We can do the follow things:

- Upgrade LDAP plugin
- Add a retry decoration on the LDAP service.
